### ISSUE TITLE
PIL.Image.LINEAR no longer exists

### ISSUE THREAD

**Issue by stortolini** [patlevin/face-detection-tflite#13]
You are using pillow==9.5.0, but despite installing all the libraries required, when executing my code I get:
```
File /opt/conda/lib/python3.10/site-packages/fdlite/transform.py:66, in image_to_tensor(image, roi, output_size, keep_aspect_ratio, output_range, flip_horizontal)
     63 dst_points = [(0., 0.), (width, 0.), (width, height), (0., height)]
     64 coeffs = _perspective_transform_coeff(src_points, dst_points)
     65 roi_image = img.transform(size=(width, height), method=Image.PERSPECTIVE,
---> 66                           data=coeffs, resample=Image.LINEAR)
     67 # free some memory - we don't need the temporary image anymore
     68 if img != image:

AttributeError: module 'PIL.Image' has no attribute 'LINEAR'
```

My code is really simple:
```
from fdlite import FaceDetection, FaceDetectionModel
from fdlite.render import Colors, detections_to_render_data, render_to_image 
from PIL import Image

image = Image.open('ff2fc5a0-22c8-4420-8e0b-1f24ea241fa4.png')
detect_faces = FaceDetection(model_type=FaceDetectionModel.BACK_CAMERA)
faces = detect_faces(image)
if not len(faces):
    print('no faces detected :(')
else:
    render_data = detections_to_render_data(faces, bounds_color=Colors.GREEN)
    render_to_image(render_data, image).show()
```

I've installed your library thanks to pip, I'm running the code on a VertexAI Jupyter Notebook.
I can't use your library, can you help me?

**Comment by patlevin** [comment]
Seems like I would need to update the dependencies to Pillow 10.3.0.

**Comment by patlevin** [comment]
@Cioffy The latest version is available via `pip` and works with pillow 10.3.0.
